### ISSUE TITLE
Is your master updated for 2.3.1 fabric?

### ISSUE THREAD

**Issue by nkaramolegos** [adityajoshi12/fabric-samples-advance-topics#2]
I am trying to follow your youtube tutorial but fails. Can you please give us some information about the version of the fabric and the commit of your repository that are used to your demo?

**Comment by nkaramolegos** [comment]
The binaries in commit 2eb75dad6c6217a34d026367f8e3bec87cddaf45 (previous day of demo) return that their version is 2.3.0. I replace them with 2.2.0, otherwise /network.sh up createChannel -c mychannel -i 2.2 fails

**Comment by adityajoshi12** [comment]
it will work with both versions 2.3 and 2.2. Please provide some details about the errors.
