### ISSUE TITLE
Error while running the caliper benchmark

### ISSUE THREAD

**Issue by ishitaa27** [adityajoshi12/fabric-samples-advance-topics#3]
Facing an error while running the caliper benchmark.

Command:
`npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig networks/networkConfig.yaml --caliper-benchconfig benchmarks/assetCCBenchmark.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled`

Screenshot of error:
![Screenshot from 2021-11-27 16-21-49](https://user-images.githubusercontent.com/65659810/143678346-0c15a445-2bbd-462e-bafb-de5f8092c146.png)

**Comment by adityajoshi12** [comment]
What's your nodejs version?

**Comment by ishitaa27** [comment]
12.15.0

**Comment by rbadrana** [comment]
Hellow Sir, I am facing the following error, even though I have checked my path 
![Screenshot from 2021-12-28 14-06-51](https://user-images.githubusercontent.com/77002515/147546595-accaa1e7-12cf-44f5-b0ae-9edec8c73e10.png)


2021.12.28-07:59:37.318 error [caliper] [cli-launch-manager]    Unexpected error during benchmark execution: Error: path property does not point to a file that exists for clientSignedCert for name client0.org1.example.com

**Comment by adityajoshi12** [comment]
Try with the absolute paths

**Comment by rbadrana** [comment]
> Try with the absolute paths

thank you sir, it worked

**Comment by jerry-98** [comment]
> > Try with the absolute paths
Hi Sir,  can you please 
give an example for the same I am unable to fix it
